name: Fuck Location CI Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - id: get-project
        name: Get project FuckLocation
        run: echo "::set-output name=PROJECT::$(cat project-to-build)"
      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} https://github.com/Mikotwa/FuckLocation.git
      - name: Build the app
        working-directory: ./FuckLocation
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: ./FuckLocation/app/build/outputs/apk/debug/app-debug.apk
      - name: Send apk to telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |+
            New push to github!
            *${{ github.event.head_commit.message }}* by ${{ github.event.head_commit.author.name }}
            See commit detail in [here](${{ github.event.head_commit.url }})
            Snapshot apk is attached
          document: ${{ github.workspace }}/FuckLocation/app/build/outputs/apk/debug/app-debug.apk
